### ISSUE TITLE
Location Icon not rendered directly after Onboarding

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OPENER-next#18]
After the onboarding or rather after allowing the app to track my location the postion maker isn't rendered.
However after closing and reopening the app the marker appears.

**Comment by 7h30n3** [comment]
We have to check if it's depending on the permission to track the location.
Possible Solution: Ask for Permission on app start and not after onboarding.

**Comment by Robbendebiene** [comment]
In the next major version of [Geolocator](https://github.com/Baseflow/flutter-geolocator) implicit permission requests will be removed (https://github.com/Baseflow/flutter-geolocator/pull/836). This might automatically fix this particular problem, however if the user first denies the location permission and grants it later on (for example by clicking the location button) the user location probably won't be visible since the `Geolocator.getPositionStream` doesn't catch this. As a workaround the Stream could be re-enabled when the permission is requested and granted by the location button.
