### ISSUE TITLE
Selecting a marker zooms in too close

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OPENER-next#57]
**Device:** Honor View 20
**OS:** Android 10
**App version:**  5d71b14

**Issue (How to reproduce):**
After clicking on a stop area click on a marker and the camera zooms in too far, so the surrounding is nearly visible anymore.

**Expected behavior:**
Don't zoom too close to the marker. See attached screenshots. Left/First as is. Right/Second as expected.

<img src="https://user-images.githubusercontent.com/18004390/154736218-2a793224-ca2a-47f4-bd9c-93b850ebb348.png" alt="First" width=300> <img src="https://user-images.githubusercontent.com/18004390/154736224-3b6accba-4319-4a41-af90-60674029214c.png" alt="Second" width=300>

**Comment by Robbendebiene** [comment]
I've now set a max zoom value of 20, because 19 could still result in some overlapping markers. See screenshots below

20 and 19:
<img src="https://user-images.githubusercontent.com/13716661/154908303-30909fb3-6ec2-4678-bfb9-989d72695acf.png"  width=300> <img src="https://user-images.githubusercontent.com/13716661/154908630-f29f6158-e095-454a-9d80-1dfdf68989f3.png"  width=300>

**Comment by 7h30n3** [comment]
Fixed by d0c4d52a206769c970a7034fe5289bf8cfefcf97
